@tool
extends SceneTree

## Phase 4 build-time helper. Generates Inter-Variable.tres + 5 FontVariation .tres
## using ResourceSaver.save() — Godot-native serialization, NOT hand-authored.
##
## NOT distributed with the addon (lives outside addons/neocade_theme/ per Cycle 6 F3 fix —
## FOUND-01 / Phase 4 SC#1 requires exactly 1 .gd file at addon root: neocade_theme.gd).
##
## **Architecture note (Rule 3 deviation from PLAN 04-02 Task 2):** The plan specified
## `extends EditorScript` driven by `godot --headless --editor --script <path>`. Per Godot 4.6
## docs (engine_details/development -> command_line_tutorial), the `-s/--script` CLI flag only
## runs scripts that extend `SceneTree` or `MainLoop`; EditorScript._run() is invoked exclusively
## by interactive editor entry points (File -> Run, Ctrl+Shift+X, FileSystem context menu, command
## palette). To preserve the plan's intent (autonomous execution, no hand-authored .tres files,
## ResourceSaver-driven serialization), this helper extends SceneTree instead, which IS runnable
## from `godot --headless --script <abs-path>`. All other plan invariants hold:
##   - Helper lives outside the addon root (Cycle 6 F3 fix preserved).
##   - .import sidecar is generated by Godot's import pass, then [params] block is enforced
##     in-place (PITFALLS 5.5 settings).
##   - All 6 .tres (Inter-Variable + 5 FontVariation) are produced via ResourceSaver.save()
##     (Cross-AI Cycle 1 C5 fix preserved — no hand-authored .tres / .import).
##   - File set, paths, and OpenType axes match DESIGN_TOKENS §8.5.
##
## Run via:
##   godot --headless --script .planning/phases/04-foundation-neocadetheme-superclass-per-theme-subclasses-font/helpers/_phase4_import.gd
##
## Prerequisite: a prior `godot --headless --import` pass must have run so the
## Inter-Variable.ttf.import sidecar exists (this helper enforces values rather than
## generating the sidecar from scratch).

func _init() -> void:
	var fonts_dir := "res://addons/neocade_theme/fonts/"

	# Step 1: load the imported FontFile.
	var inter_ttf: FontFile = load(fonts_dir + "Inter-Variable.ttf") as FontFile
	if inter_ttf == null:
		push_error("Inter-Variable.ttf failed to import. Run `godot --headless --import` first.")
		quit(1)
		return

	# Step 2: enforce the GL-Compatibility-correct import settings (PITFALLS 5.5 + STACK).
	# Importer params are file-side, not resource-side, so we mutate the .import file directly.
	# This keeps the Godot-generated header/UID/dest_files exactly as Godot wrote them — only the
	# `[params]` values are normalized to match the plan's required matrix.
	var import_path := fonts_dir + "Inter-Variable.ttf.import"
	var fa := FileAccess.open(import_path, FileAccess.READ)
	if fa == null:
		push_error("Inter-Variable.ttf.import was not generated by the editor import pass. " +
			"Run `godot --headless --import` first.")
		quit(1)
		return
	var raw := fa.get_as_text()
	fa.close()

	var required := {
		"antialiasing": "1",                          # Grayscale (PITFALLS 5.5)
		"hinting": "1",                               # Light
		"subpixel_positioning": "2",                  # Auto
		"generate_mipmaps": "true",
		"allow_system_fallback": "true",
		"multichannel_signed_distance_field": "false",
	}
	var mutated := raw
	for k in required.keys():
		var pattern := RegEx.new()
		pattern.compile("(?m)^%s=.*$" % k)
		var m := pattern.search(mutated)
		if m:
			mutated = pattern.sub(mutated, "%s=%s" % [k, required[k]])
		else:
			# Append under [params] if missing.
			mutated = mutated.replace("[params]\n", "[params]\n%s=%s\n" % [k, required[k]])
	var fb := FileAccess.open(import_path, FileAccess.WRITE)
	fb.store_string(mutated)
	fb.close()

	# Step 3: author Inter-Variable.tres FontFile wrapper via ResourceSaver.
	# The wrapper exists so consumers have a stable preload-able resource path
	# (FontVariation.base_font expects a Font resource).
	var inter_tres_path := fonts_dir + "Inter-Variable.tres"
	var save_ok := ResourceSaver.save(inter_ttf, inter_tres_path)
	if save_ok != OK:
		push_error("Failed to save Inter-Variable.tres: error %d" % save_ok)
		quit(1)
		return

	# Step 4: author 5 FontVariation .tres files via ResourceSaver.
	# Each uses Inter-Variable.tres as base_font + sets variation_opentype.
	var inter_base: FontFile = load(inter_tres_path) as FontFile
	if inter_base == null:
		push_error("Inter-Variable.tres failed to load after save")
		quit(1)
		return

	var variants := [
		{"file": "Inter-HeaderLarge.tres",  "wght": 800, "opsz": 32},
		{"file": "Inter-HeaderMedium.tres", "wght": 700, "opsz": 32},
		{"file": "Inter-HeaderSmall.tres",  "wght": 600, "opsz": 24},
		{"file": "Inter-Body.tres",         "wght": 400, "opsz": -1},  # opsz omitted
		{"file": "Inter-Caption.tres",      "wght": 400, "opsz": -1},
	]
	for v in variants:
		var fv := FontVariation.new()
		fv.base_font = inter_base
		var open_type := {"wght": v.wght}
		if v.opsz > 0:
			open_type["opsz"] = v.opsz
		fv.variation_opentype = open_type
		var ok := ResourceSaver.save(fv, fonts_dir + v.file)
		if ok != OK:
			push_error("Failed to save %s: error %d" % [v.file, ok])
			quit(1)
			return

	print("[Phase 4] font materialization complete: TTF imported, .import params enforced, ",
		"Inter-Variable.tres + 5 FontVariation .tres files saved via ResourceSaver.")
	quit(0)
