@tool
extends EditorScript

## Phase 4 build-time helper. Empirically introspects every targeted Control's
## Theme.get_<datatype>_list("Type") in Godot 4.6 and emits a BINDING_TABLE_SEED.txt
## with the slot names per (Type, datatype) tuple. Task 2 of Plan 04-05 reads the
## seed VERBATIM into BINDING_TABLE's slot keys; recipes (value formulas) are added
## by hand per the M3 design system.
##
## NOT distributed (lives outside addons/neocade_theme/). Run via:
##   godot --headless --editor --script .planning/phases/04-foundation-neocadetheme-superclass-per-theme-subclasses-font/helpers/_phase4_introspect.gd
##
## Output goes to .planning/phases/04-foundation-neocadetheme-superclass-per-theme-subclasses-font/helpers/BINDING_TABLE_SEED.txt
##
## Cycle 6 F7 fix 2026-05-06: slot-name source-of-truth changed from
## MINIMAL-THEME-DISSECTION.md (curated) to this empirical introspection. Where
## the seed and the dissection disagree, the seed wins (Cycle 6 F4 root cause:
## dissection had `on`/`off` for CheckButton; the seed has `checked`/`unchecked`
## because that's what Godot 4.6 actually uses).

func _run() -> void:
	# The 37 Control types Phase 4 BINDING_TABLE must cover (from MINIMAL-THEME-COVERAGE-DELTA.md).
	# Order matches CANONICAL_SLOT_NAMES freeze ordering.
	var types: Array[String] = [
		"Button", "CheckBox", "CheckButton", "OptionButton", "MenuButton", "MenuBar",
		"LinkButton", "LineEdit", "TextEdit", "CodeEdit", "RichTextLabel", "Label",
		"SpinBox", "ProgressBar", "HSlider", "VSlider", "HScrollBar", "VScrollBar",
		"Tree", "ItemList", "TabBar", "TabContainer", "PanelContainer", "Panel",
		"PopupPanel", "PopupMenu", "TooltipPanel", "TooltipLabel",
		"AcceptDialog", "ConfirmationDialog", "FileDialog", "Window",
		"HSeparator", "VSeparator", "HSplitContainer", "VSplitContainer",
		"HFlowContainer", "ColorPicker", "ColorPickerButton",
		"GraphEdit", "GraphFrame", "GraphNode", "FoldableContainer",
	]
	var data_types: Array[String] = ["stylebox", "color", "constant", "font_size", "icon"]
	var lines: Array[String] = []
	lines.append("# BINDING_TABLE_SEED — empirically generated by _phase4_introspect.gd")
	lines.append("# Source: Godot 4.6 ThemeDB / Theme.get_<datatype>_list API")
	lines.append("# Generated: " + Time.get_datetime_string_from_system())
	lines.append("# Consume: Task 2 of Plan 04-05 — slot lists per (Type, datatype) become BINDING_TABLE keys.")
	lines.append("")

	for t in types:
		lines.append("## " + t)
		for dt in data_types:
			# Godot's ThemeDB exposes per-class default theme items via _get_default_theme().
			# We probe each (Type, datatype) tuple by querying the editor default theme.
			var default_theme: Theme = ThemeDB.get_default_theme()
			if default_theme == null:
				push_error("ThemeDB.get_default_theme() returned null — re-run from editor")
				return
			var slot_list: PackedStringArray
			match dt:
				"stylebox":  slot_list = default_theme.get_stylebox_list(t)
				"color":     slot_list = default_theme.get_color_list(t)
				"constant":  slot_list = default_theme.get_constant_list(t)
				"font_size": slot_list = default_theme.get_font_size_list(t)
				"icon":      slot_list = default_theme.get_icon_list(t)
			if slot_list.size() == 0:
				continue
			var slots: Array[String] = []
			for s in slot_list:
				slots.append(s)
			slots.sort()  # deterministic ordering for diff-friendliness
			lines.append("  " + dt + ": " + ", ".join(slots))
		lines.append("")

	var out_path := ".planning/phases/04-foundation-neocadetheme-superclass-per-theme-subclasses-font/helpers/BINDING_TABLE_SEED.txt"
	var fa := FileAccess.open(out_path, FileAccess.WRITE)
	assert(fa != null, "Failed to open %s for writing" % out_path)
	fa.store_string("\n".join(lines))
	fa.close()
	print("BINDING_TABLE_SEED.txt emitted at: ", out_path)
